name: Expresiones
run-name: expresiones-gh_actions

on:
  push:
    branches:
      - main
      - aprendiendo**

  pull_request:
    branches:
      - main
      - dev
      - aprendiedo**
      
  workflow_dispatch: 
    inputs:
      edad:
        description: 'tu edad'
        required: true
        default: 18
        type: integer
      
      nombre:
        description: 'tu nombre'
        required: true
        type: string

env:
  DAY_OF_WEEK: Monday
  First_Name: ${{ github.actor }}

jobs:
  mi-main-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - name: definir_rama
      run: echo "ENVIRONMET=main" >> $GITHUB_ENV

    - name: definir_rama
      run: echo "estamos en la rama $ENVIRONMET"

    - name: check-repo-changes
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: script-runing
      run: python hello_world.py
  
  job-secundario:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello it's Monday!"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"   

  job-dispatch-mayor:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.edad >= 18 }}
    runs-on: ubuntu-latest
    steps:
    - name: print_es_mayor
      run: echo "${{ inputs.nombre }} es mayor de edad"

  job-dispatch-menor:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.edad < 18 }}
    runs-on: ubuntu-latest
    steps:
    - name: print_es_mayor
      run: echo "${{ inputs.nombre }} es menor de edad"
