name: Python application
run-name: Mi primer workflow en gh actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: check-repo-changes
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: script-runing
      run: python hello_world.py